# Generated by Django 3.1.3 on 2021-01-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210116_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите картинку к посту.', null=True, upload_to='posts/', verbose_name='Изображение: '),
        ),
    ]
