# Generated by Django 3.1.3 on 2021-01-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210117_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Укажите адрес сообщества в интернете.', max_length=100, unique=True, verbose_name='Ключ для составления адреса: '),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Можете выбрать группу, к которой будет принадлежать пост.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.group', verbose_name='Группа: '),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Можете выбрать картинку к посту.', null=True, upload_to='posts/', verbose_name='Изображение: '),
        ),
    ]
